spring.application.name=epouvante

# ===============================
# DATABASE
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/epouvante
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER
# ===============================

server.port=8080

# ===============================
# THYMELEAF
# ===============================

spring.thymeleaf.cache=false

# ===============================
# LOGS
# ===============================

logging.level.org.springframework.security=DEBUG

# ===============================
# SECURITY (PASSWORDS HASHÉS)
# ===============================

# user1 -> user123
app.security.user1.password=$2y$10$1XHSrULY2b0UpbvGJYX1IOkhmatzKK4rylswnCi0MqvwDcvYKDgFi

# user2 -> user123
app.security.user2.password=$2y$10$1XHSrULY2b0UpbvGJYX1IOkhmatzKK4rylswnCi0MqvwDcvYKDgFi

# admin -> admin123
app.security.admin.password=$2y$10$i09CT0dfsRtlCYZSMW3W0uIUCuv3wh7kHZEbmoL4sk9PUV360Jb3.