name: CI/CD - Petite Maison Epouvante

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  backend-ci-cd:
    name: Build, test, dockerize, scan, publish and load test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/epouvante

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: epouvante
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Installer Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Rendre mvnw executable
        run: chmod +x mvnw

      - name: Compiler et lancer les tests
        run: ./mvnw clean verify

      - name: Definir le nom de l'image Docker
        run: echo "IMAGE_NAME=ghcr.io/sakuradiop/epouvante-backend:latest" >> $GITHUB_ENV

      - name: Construire image Docker
        run: docker build -t $IMAGE_NAME .

      - name: Scanner image Docker avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

      - name: Connexion au registre Docker GitHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publier image Docker dans GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        run: docker push $IMAGE_NAME

      - name: Demarrer application Spring Boot pour test de charge
        run: |
          SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/epouvante \
          SPRING_DATASOURCE_USERNAME=admin \
          SPRING_DATASOURCE_PASSWORD=admin \
          nohup ./mvnw spring-boot:run > app.log 2>&1 &

      - name: Attendre que l'application soit disponible
        run: |
          for i in {1..90}; do
            if curl -s http://localhost:8080/actuator/health | grep UP; then
              echo "Application demarree"
              exit 0
            fi
            echo "En attente de l'application..."
            sleep 2
          done

          echo "Application non disponible"
          echo "===== LOGS APPLICATION ====="
          cat app.log
          exit 1

      - name: Lancer test de charge k6
        run: |
          docker run --rm --network host \
            -e BASE_URL=http://localhost:8080 \
            -v $GITHUB_WORKSPACE:/workspace \
            grafana/k6 run /workspace/tests/load/annonces-load-test.js