  k6-load-test:
    name: Load testing with k6
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/epouvante

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: epouvante
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Installer Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Rendre mvnw executable
        run: chmod +x mvnw

      - name: Demarrer application Spring Boot
        run: |
          ./mvnw spring-boot:run &
          sleep 40

      - name: Installer k6
        run: |
          sudo gpg -k
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Lancer test de charge k6
        run: |
          k6 run ../../tests/load/annonces-load-test.js